export const hard_Data = [
  {
    info: {
      id: "193479",
      name: "Haldiram's",
      cloudinaryImageId:
        "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/hnxwug8pbnby5ftshubz",
      locality: "Kucha Mahajani",
      areaName: "Chandni Chowk",
      costForTwo:350,
      cuisines: ["Sweets", "Snacks", "North Indian"],
      avgRatingString: "4.3",
      totalRatingsString: "1K+",
      isOpen: true,
      quantity:1,
    },
  },
  {
    info: {
      id: "169483",
      name: "Bakingo",
      cloudinaryImageId:
        "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/igl34lywkjmuuqtyjac5",
      locality: "West Arjun Nagar",
      areaName: "Krishna Nagar",
      costForTwo:300,
      cuisines: ["Bakery", "Desserts", "Beverages", "Snacks"],
      avgRatingString: "4.3",
      totalRatingsString: "10K+",
      isOpen: true,
      quantity:1,
    },
  },
  {
    info: {
      id: "89841",
      name: "KFC",
      cloudinaryImageId:
        "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/56c9ab92bd79745fd152a30fa2525426",
      locality: "Swami Dayanand Marg",
      areaName: "Krishna Nagar",
      costForTwo:400,
      cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
      avgRatingString: "4.0",
      totalRatingsString: "10K+",
      isOpen: true,
      quantity:1,
    },
  },
  {
    info: {
      id: "253727",
      name: "McDonald's",
      cloudinaryImageId:
        "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/6dc3ed2ca21d71acff7c2a51dfe4c720",
      locality: "Kashmere Gate Metro Station",
      areaName: "Kashmiri Gate",
      costForTwo:400,
      cuisines: ["American"],
      avgRatingString: "4.2",
      totalRatingsString: "1K+",
      isOpen: true,
      quantity:1,
    },
  },
  {
    info: {
      id: "79716",
      name: "Burger King",
      cloudinaryImageId:
        "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/e33e1d3ba7d6b2bb0d45e1001b731fcf",
      locality: "Aditya Mega Mall",
      areaName: "Shahdara",
      costForTwo:350,
      cuisines: ["Burgers", "American"],
      avgRatingString: "4.1",
      totalRatingsString: "10K+",
      isOpen: true,
      quantity:1,
    },
  },
  {
    info: {
      id: "397778",
      name: "Pizza Hut",
      cloudinaryImageId:
        "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/2b4f62d606d1b2bfba9ba9e5386fabb7",
      locality: "Shahdara",
      areaName: "Krishna Nagar",
      costForTwo:350,
      cuisines: ["Pizzas"],
      avgRatingString: "3.5",
      totalRatingsString: "1K+",
      isOpen: true,
      quantity:1,
    },
  },
  {
    info: {
      id: "350774",
      name: "Subway",
      cloudinaryImageId:
        "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/1ace5fa65eff3e1223feb696c956b38b",
      locality: "Satanam Road",
      areaName: "Krishna Nagar",
      costForTwo:350,
      cuisines: ["Fast Food", "Salads", "Snacks", "Desserts", "Beverages"],
      avgRatingString: "3.9",
      totalRatingsString: "1K+",
      isOpen: true,
      quantity:1,
    },
  },
  {
    info: {
      id: "107452",
      name: "Chaayos Chai+Snacks=Relax",
      cloudinaryImageId:
        "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/cef7835bd5c399d6adb44a4c24e037dd",
      locality: "Kashmere Gate Metro Station",
      areaName: "Kashmiri Gate",
      costForTwo:250,
      cuisines: [
        "Bakery",
        "Beverages",
        "Chaat",
        "Desserts",
        "Home Food",
        "Italian",
        "Maharashtrian",
        "Snacks",
        "Street Food",
        "Sweets",
      ],
      avgRatingString: "4.2",
      totalRatingsString: "1K+",
      isOpen: true,
      quantity:1,
    },
  },
  {
    info: {
      id: "234208",
      name: "Theobroma",
      cloudinaryImageId:
        "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/b033728dcb0101ceb19bff0e1e1f6474",
      locality: "Swasthya Vihar",
      areaName: "Laxmi Nagar",
      costForTwo:800,
      cuisines: ["Bakery", "Desserts"],
      avgRatingString: "4.4",
      totalRatingsString: "5K+",
      isOpen: true,
      quantity:1,
    },
  },
  {
    info: {
      id: "110648",
      name: "Bikanervala",
      cloudinaryImageId:
        "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/qkiuqrk7jwh3bvj13hxo",
      locality: "Satanam Marg",
      areaName: "Krishna Nagar",
      costForTwo:500,
      cuisines: [
        "Chinese",
        "North Indian",
        "South Indian",
        "Desserts",
        "Sweets",
      ],
      avgRatingString: "4.0",
      totalRatingsString: "5K+",
      isOpen: true,
      quantity:1,
    },
  },
  {
    info: {
      id: "105992",
      name: "NIC Ice Creams",
      cloudinaryImageId:
        "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/c8b98c4064dc2fd6bdf350212e5f0bd5",
      locality: "556th Scheme",
      areaName: "Dilshad Gardens",
      costForTwo:120,
      cuisines: ["Ice Cream", "Desserts"],
      avgRatingString: "4.5",
      totalRatingsString: "10K+",
      isOpen: true,
      quantity:1,
    },
  },
  {
    info: {
      id: "395804",
      name: "L'Opera",
      cloudinaryImageId:
        "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/f60300943f5c60b3b888af6dbfb77ca3",
      locality: "Railway Colony",
      areaName: "Civil Lines",
      costForTwo: 600,
      cuisines: ["Bakery", "Cafe", "French", "Desserts", "Continental"],
      avgRatingString: "4.1",
      totalRatingsString: "100+",
      isOpen: true,
      quantity:1,
    },
  },
  {
    info: {
      id: "387312",
      name: "Wat-a-Burger! - India ka Burger",
      cloudinaryImageId:
        "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/bngnkrkz1rxbifxpesfd",
      locality: "Krishna Nagar",
      areaName: "Krishna Nagar",
      costForTwo:250,
      cuisines: [
        "Burgers",
        "Fast Food",
        "Continental",
        "American",
        "Beverages",
        "Desserts",
      ],
      avgRatingString: "3.7",
      totalRatingsString: "1K+",
      isOpen: true,
      quantity:1,
    },
  },
  {
    info: {
      id: "355345",
      name: "Grameen Kulfi",
      cloudinaryImageId:
        "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/ghxzk3nxotwhwtitt1eo",
      locality: "556th Scheme",
      areaName: "Dilshad Gardens",
      costForTwo:120,
      cuisines: ["Ice Cream", "Desserts"],
      avgRatingString: "4.5",
      totalRatingsString: "500+",
      isOpen: true,
      quantity:1,
    },
  },
  {
    info: {
      id: "330934",
      name: "Havmor Havfunn Ice Cream",
      cloudinaryImageId:
        "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/49845b494b1e637209b7bd1c7ca184ad",
      locality: "Anand Vihar",
      areaName: "Karkardooma",
      costForTwo:400,
      cuisines: ["Ice Cream", "Ice Cream Cakes", "Desserts", "Beverages"],
      avgRatingString: "4.4",
      totalRatingsString: "100+",
      isOpen: true,
      quantity:1,
    },
  },
  {
    info: {
      id: "427432",
      name: "Nirula's",
      cloudinaryImageId:
        "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/94c82b9d46792c198fff64899ff05bd2",
      locality: "Vishwas Nagar",
      areaName: "Dilshad Gardens",
      costForTwo:500,
      cuisines: [
        "Pizzas",
        "Burgers",
        "Ice Cream",
        "North Indian",
        "Fast Food",
        "Pastas",
        "Beverages",
      ],
      avgRatingString: "3.8",
      totalRatingsString: "100+",
      isOpen: true,
      quantity:1,
    },
  },
  {
    info: {
      id: "38928",
      name: "Domino's Pizza",
      cloudinaryImageId:
        "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/ajzfwd97o86feojkwoju",
      locality: "Paharganj",
      areaName: "Paharganj",
      costForTwo:400,
      cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
      avgRatingString: "4.2",
      totalRatingsString: "10K+",
      isOpen: true,
      quantity:1,
    },
  },
  {
    info: {
      id: "214710",
      name: "La Pino'z Pizza",
      cloudinaryImageId:
        "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/bbzvsjc394c9a803en4i",
      locality: "Karkardooma",
      areaName: "Karkardooma",
      costForTwo:300,
      cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
      avgRatingString: "3.8",
      totalRatingsString: "5K+",
      isOpen: true,
      quantity:1,
    },
  },
  {
    info: {
      id: "40330",
      name: "Sagar Ratna",
      cloudinaryImageId:
        "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/ldjgyyvkgxc9x05acxb6",
      locality: "S Block",
      areaName: "Krishna Nagar",
      costForTwo:600,
      cuisines: ["South Indian", "North Indian", "Chinese", "Desserts"],
      avgRatingString: "4.2",
      totalRatingsString: "1K+",
      isOpen: true,
      quantity:1,
    },
  },
  {
    info: {
      id: "160829",
      name: "Keventers - Milkshakes & Desserts",
      cloudinaryImageId:
        "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/f0e94c984813053f46c214f18ce73d59",
      locality: "Agarwal Fun City Metro Mall",
      areaName: "Maharishi Valmiki Marg",
      costForTwo:200,
      cuisines: ["Beverages", "Ice Cream", "Desserts", "Healthy Food"],
      avgRatingString: "4.0",
      totalRatingsString: "1K+",
      isOpen: true,
      quantity:1,
    },
  },
];
